openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /pet:
    get:
      operationId: getPet
      responses:
        '200':
          description: Successful operation