openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https'

paths:
  /assumptions:
    get:
      operationId: getAllAssumptions
      responses:
        '200':
          description: Successful operation
    post:
      operationId: addAssumptions
      responses:
        '200':
          description: Successful operation
