openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https'

paths:

components:
  responses:
    ClientError:
      description: Client error
      content:
        application/json:
          schema:
            $ref: "commons.yaml#/components/schemas/Error"
    ServerError:
      description: Server error
      content:
        application/json:
          schema:
            $ref: "commons.yaml#/components/schemas/Error"
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        description:
          type: string
