openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https'

components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        description:
          type: string
