openapi: 3.0.3
info:
  title: Expenses
  description: Title
  version: 1.0.0
servers:
  - url: 'http'
paths:
  /expenses:
    get:
      operationId: getExpenses
      responses:
        '200':
          description: Successfully acquired all expenses
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExpensesDto"
        '400':
          $ref: "commons.yaml#/components/responses/ClientError"
        '500':
          $ref: "commons.yaml#/components/responses/ServerError"
    post:
      operationId: addExpense
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExpenseCreateDto"
      responses:
        '200':
          description: Expense has been created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExpensesDto"
        '400':
          $ref: "commons.yaml#/components/responses/ClientError"
        '500':
          $ref: "commons.yaml#/components/responses/ServerError"
  /expenses/{id}:
    get:
      operationId: getExpense
      responses:
        '200':
          description: Successfully acquired expense
        '400':
          $ref: "commons.yaml#/components/responses/ClientError"
        '500':
          $ref: "commons.yaml#/components/responses/ServerError"
    patch:
      operationId: modifyExpense
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PatchExpenseDto"
      responses:
        '200':
          description: Successfully modified expense
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExpensesDto"
        '400':
          $ref: "commons.yaml#/components/responses/ClientError"
        '500':
          $ref: "commons.yaml#/components/responses/ServerError"
    delete:
      operationId: deleteExpense
      responses:
        '200':
          description: Expense has been deleted successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ExpensesDto"
        '400':
          $ref: "commons.yaml#/components/responses/ClientError"
        '500':
          $ref: "commons.yaml#/components/responses/ServerError"

components:
  schemas:
    ExpenseDto:
      type: object
      properties:
        category:
          type: string
          required: true
        subcategory:
          type: string
          required: true
        price:
          type: integer
          description: Cost in cents
          required: true
        date:
          description: Time is in unix timestamp
          type: integer
          format: int64
          required: true
    PatchExpenseDto:
      type: object
      properties:
        category:
          type: string
          required: false
        subcategory:
          type: string
          required: false
        price:
          type: integer
          description: Cost in cents
          required: false
        date:
          type: integer
          format: int64
          required: false
    ExpenseCreateDto:
      type: object
      properties:
        creationBody:
          $ref: "#/components/schemas/ExpenseDto"
    ExpensesDto:
      type: array
      items:
        $ref: "#/components/schemas/ExpenseDto"
